# Generated by Django 5.1.1 on 2024-09-04 19:17

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_employee_email_remove_employee_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('residency', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('refugee', 'Refugee'), ('other', 'Other')], max_length=20)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
