# Generated by Django 5.1.1 on 2024-09-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_refugee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
