# Generated by Django 5.1.2 on 2024-10-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_question_question_type_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='rodo_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refugee',
            name='truth_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
