# Generated by Django 5.1.2 on 2024-10-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_refugee_rodo_consent_refugee_truth_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='awarded_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
