# Generated by Django 5.1.2 on 2024-10-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_question_max_points_useranswer_awarded_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetest',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
