# Generated by Django 5.1.2 on 2024-10-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_languagetest_langage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagetest',
            old_name='langage',
            new_name='language',
        ),
    ]
