# Generated by Django 5.1.2 on 2024-10-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_langage_languagetest_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='languagecourse',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.language'),
        ),
        migrations.AlterField(
            model_name='languagetest',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.language'),
        ),
    ]
