# Generated by Django 5.1.2 on 2024-10-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_language_alter_languagecourse_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.language'),
            preserve_default=False,
        ),
    ]
