# Generated by Django 5.1.2 on 2024-11-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_refugee_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='base.languagecourse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('open', 'Otwarte'), ('choice', 'Zamknięte')], max_length=15),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Poniedziałek'), ('Tue', 'Wtorek'), ('Wed', 'Środa'), ('Thu', 'Czwartek'), ('Fri', 'Piątek')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.languagecourse')),
                ('teacher', models.ForeignKey(limit_choices_to={'courses__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
