# Generated by Django 5.1.3 on 2024-11-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_classroom_employee_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Przedział godzinowy',
                'verbose_name_plural': 'Przedziały godzinowe',
                'ordering': ['start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='time_interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.timeinterval', verbose_name='Przedział godzinowy'),
        ),
    ]
