# Generated by Django 5.1.3 on 2024-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_timeinterval_available_classrooms_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecourse',
            name='weekly_classes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
