# Generated by Django 5.1.3 on 2024-11-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_languagecourse_weekly_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='conflicts',
            field=models.IntegerField(default=0),
        ),
    ]
