# Generated by Django 5.1.3 on 2024-12-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_classschedule_conflicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='languagecourse',
            name='semesters',
            field=models.ManyToManyField(related_name='courses', to='base.semester'),
        ),
    ]
