# Generated by Django 5.1.3 on 2024-12-19 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_semester_start_date_alter_semester_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTestThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_points', models.PositiveIntegerField()),
                ('max_points', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_thresholds', to='base.languagecourse')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.languagetest')),
            ],
        ),
    ]
