# Generated by Django 5.1.3 on 2024-12-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_coursetestthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='refugees', to='base.languagecourse'),
        ),
    ]
