# Generated by Django 5.1.3 on 2024-12-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_refugee_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetestthreshold',
            name='max_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursetestthreshold',
            name='min_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
