# Generated by Django 5.1.3 on 2024-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_coursetestthreshold_max_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetestthreshold',
            name='is_slavic',
            field=models.BooleanField(default=False),
        ),
    ]
