# Generated by Django 5.1.3 on 2024-12-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='base.semester'),
        ),
    ]
