# Generated by Django 5.1.3 on 2024-12-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_recruitment_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
