# Generated by Django 5.1.3 on 2024-12-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_recruitment_max_people_alter_recruitment_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='manually_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='max_people',
            field=models.IntegerField(default=1000000, verbose_name='Maksymalna ilość zarekrutowanych osób'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='base.semester', verbose_name='Na semestr'),
        ),
    ]
