# Generated by Django 5.1.3 on 2024-12-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_recruitment_manually_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='language_tests',
            field=models.ManyToManyField(blank=True, related_name='recruitments', to='base.languagetest', verbose_name='Testy językowe'),
        ),
    ]
