# Generated by Django 5.1.3 on 2024-12-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_recruitment_language_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagetest',
            name='is_current',
        ),
    ]
