# Generated by Django 5.1.3 on 2024-12-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_useranswer_refugee_filledtest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='completed_test',
            new_name='filled_test',
        ),
    ]
