# Generated by Django 5.1.3 on 2024-12-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_completed_test_useranswer_filled_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetestthreshold',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_test_thresholds', to='base.recruitment'),
        ),
    ]
