# Generated by Django 5.1.3 on 2024-12-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_coursetestthreshold_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
