# Generated by Django 5.1.3 on 2024-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_recruitment_activated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nazwa rekrutacji'),
        ),
    ]
