# Generated by Django 5.1.3 on 2025-01-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_recruitment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledtest',
            name='test_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='choice_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='max_points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.choice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.question'),
        ),
    ]
