# Generated by Django 5.1.3 on 2025-01-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_filledtest_test_snapshot_useranswer_choice_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filledtest',
            name='test_snapshot',
        ),
        migrations.AlterField(
            model_name='languagetest',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Obecny'), ('absent', 'Nieobecny'), ('late', 'Spóźniony'), ('excused absence', 'Nieobecny usprawiedliwiony')], default='absent', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='base.refugee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='base.classschedule')),
            ],
            options={
                'unique_together': {('schedule', 'refugee', 'date')},
            },
        ),
    ]
