# Generated by Django 5.1.4 on 2025-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_filledtest_test_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='email',
            field=models.EmailField(default='example@exp.pl', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
