# Generated by Django 5.1.4 on 2025-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_refugee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecourse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
