# Generated by Django 5.1.5 on 2025-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_remove_refugee_dob_refugee_is_adult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Odbiorca')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Wysłano')),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Obecny'), ('absent', 'Nieobecny'), ('late', 'Spóźniony'), ('excused absence', 'Nieobecny usprawiedliwiony'), ('not_recorded', 'Nie wpisano obecności')], default='not_recorded', max_length=20),
        ),
    ]
