# Generated by Django 5.1.5 on 2025-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_emailmessage_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('registration', 'Rejestracja na kurs'), ('removal', 'Usunięcie z kursu'), ('info', 'Informacje ogólne')], max_length=50, unique=True, verbose_name='Typ e-maila')),
                ('subject', models.CharField(max_length=255, verbose_name='Temat')),
                ('body', models.TextField(verbose_name='Treść')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='email_content',
            field=models.TextField(blank=True, default="Dzień dobry,\n\nOtrzymaliśmy Państwa zgłoszenie na kurs językowy. Zgłoszenie zostanie teraz rozpatrzone, a my skontaktujemy się z Państwem wkrótce z dalszymi informacjami.\n\nPozdrawiamy,\nZespół JRS\n\nHello,\n\nWe have received your registration for the language course. Your application will be reviewed, and we will contact you soon with further details.\n\nBest regards,\nJRS Team\n\nДобрий день,\n\nМи отримали вашу реєстрацію на мовний курс. Заявка буде розглянута, і ми зв'яжемося з вами найближчим часом для надання подальшої інформації.\n\nЗ найкращими побажаннями,\nКоманда JRS\n\nمرحبا،\n\nلقد استلمنا تسجيلك لدورة اللغة. سيتم مراجعة طلبك، وسنتواصل معك قريبًا لتزويدك بمزيد من المعلومات.\n\nمع أطيب التحيات،\nفريق JRS\n\nHola,\n\nHemos recibido su inscripción para el curso de idiomas. Su solicitud será revisada y nos pondremos en contacto con usted pronto con más detalles.\n\nSaludos,\nEquipo JRS\n", help_text='Domyślna treść e-maila wysyłanego rejestrującym się uchodźcom.', null=True, verbose_name='Treść e-maila'),
        ),
    ]
