# Generated by Django 5.1.5 on 2025-01-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_emailtemplate_delete_emailmessage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
