# Generated by Django 5.1.5 on 2025-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_delete_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='cancelled_dates',
            field=models.JSONField(blank=True, default=list, help_text='Lista dat, w których zajęcia zostały odwołane.', verbose_name='Odwołane daty'),
        ),
    ]
