# Generated by Django 5.1.5 on 2025-01-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_classschedule_cancelled_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee',
            name='attended_course',
            field=models.BooleanField(default=False),
        ),
    ]
